---
endpoints: 
  - 
    id: http
    host-env: DOCKY_HOST
    protocol: http
    port-env: DOCKY_PORT
    name: HTTP
links:  []
name: docky
id: docky
entrypoint: service.p6
cro: 1
env:  []
ignore:
  - static/css/
  - ui-samples/
  - static/js/search.js
...
