version: "3.9"
services:
  upstream:
    # can build:
    # build:
    #  context: .
    #  dockerfile: infra/Dockerfile.cro
    # for fast deployment private repo is used:
    image: rakudocs/neo.docs.raku.org
    network_mode: host
    container_name: upstream
    env_file:
      - e.env

  nginx:
    build:
      context: infra
      dockerfile: Dockerfile.nginx
    container_name: nginx
    network_mode: host
    restart: always
    depends_on:
      - upstream
